### PR TITLE
Fixed issues

### PR DESCRIPTION
**Pull request by zmax**
- PHP required version
- `$templateName` variable issue

### CODE REVIEW

**Comment by antonioribeiro** [comment]
What is this fixing exactly?
Can you provide some context?

**Comment by zmax** [comment]
Laravel: 8.x
PHP: 7.4

```
Error: Cannot use object of type App\Repositories\...Repository as array (RepostoryTrait.php at line 99)
```
We will get an error exception if we didn't set `$templateName` property in any one of transformer/repository/model class files.

In my opinion, why we'll have to set `$templateName` property even we don't need it?
If we need it or need a default value. depends on needs, set it directly in base transformer or getting it from database via model, maybe will more suitable. 

Could I have your advice on this? thank you.

**Comment by antonioribeiro** [comment]
But if you remove 

```
$objects[] = $this;
```

Transformers won't be able to find the `$templateName` on the repository even if we define it. I believe the solution for the problem you are reporting, is to make it optional and not mandatory, but still support it.

**Comment by zmax** [comment]
https://github.com/area17/twill-transformers/compare/master...zmax:fix-issue-templatename

I don't know why couldn't catch error exception in current way. so I try to check it before accessing to avoid that error exception, and it works. 

Should I create a new pull request for this?

**Pull request closed without merging**
